### ISSUE TITLE
Error on json parse

### ISSUE THREAD

**Issue by kiokumicu** [Zewo/JSON#16]
I got error when parsing JSON
`fatal error: high- and low-surrogate code points are not valid Unicode scalar values` in https://github.com/Zewo/JSON/blob/master/Source/JSONInterchangeDataParser.swift#L221
In JSON i have symbols like `\ud83d\ude24`

**Comment by IanKeen** [comment]
I am also seeing this :(

**Comment by Danappelxx** [comment]
This has been fixed in Quark, fix will be brought back here soon :)

**Comment by paulofaria** [comment]
Happened!
