### ISSUE TITLE
can't interpolate strings

### ISSUE THREAD

**Issue by tannernelson** [Zewo/JSON#6]
Serializations like this

```swift
let json = JSON.from([
   "name": "\(name)"
])
```

Result in this:

```json
{
    "name": "String(_core: Swift._StringCore(_baseAddress: Swift.OpaquePointer(_rawValue: (Opaque Value)), _countAndFlags: Swift.UInt(_value: (Opaque Value)), _owner: Swift.Optional<Swift.AnyObject>.none))String(_core: Swift._StringCore(_baseAddress: Swift.OpaquePointer(_rawValue: (Opaque Value)), _countAndFlags: Swift.UInt(_value: (Opaque Value)), _owner: Swift.Optional<Swift.AnyObject>.some(Swift._HeapBufferStorage<Swift._StringBufferIVars, Swift.UInt16>)))String(_core: Swift._StringCore(_baseAddress: Swift.OpaquePointer(_rawValue: (Opaque Value)), _countAndFlags: Swift.UInt(_value: (Opaque Value)), _owner: Swift.Optional<Swift.AnyObject>.none))"
}
```

And if you try to do 

```swift
let name: String = "test"
let json = JSON.from([
   "name": name
])
```

You'll get an error like `Cannot create JSON from type [String: String]`

**Comment by Danappelxx** [comment]
The first example works fine for me... perhaps you did something silly like `String(String)` (hence giving you that strange signature)? Either way, I added a test so that you can run it locally if you'd like.

The second example should be
```swift
let name: String = "test"
let json: JSON = [
    "name": JSON.from(name)
]
```

**Comment by tannernelson** [comment]
Maybe it's a weird cross module issue. I'll look into it some more.

**Comment by tannernelson** [comment]
Doing this worked.

```let name: String = "test"
let json: JSON = [
    "name": JSON.from(name)
]```

**Comment by Danappelxx** [comment]
Does the interpolated version not work? Are you sure that your variable was of the correct type?

**Comment by tannernelson** [comment]
Yeah. I think it's a cross module bug. I just added an extension to String in my module that wraps `return JSON.from(string)` and it's working now.
